# Generated by Django 5.0.6 on 2024-07-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicestroke',
            name='mis_hit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='practicestroke',
            name='result_distance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='practicestroke',
            name='result_side',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
