# Generated by Django 4.2.13 on 2024-06-24 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('putts', models.IntegerField()),
                ('gir', models.BooleanField()),
                ('gld', models.BooleanField()),
                ('scrambling', models.BooleanField(null=True)),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.hole')),
            ],
        ),
        migrations.CreateModel(
            name='Stroke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke', models.IntegerField()),
                ('club', models.CharField(max_length=50)),
                ('distance', models.IntegerField()),
                ('start_coordinate', models.JSONField()),
                ('end_coordinate', models.JSONField(null=True)),
                ('hole_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.holescore')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('tees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.tee')),
            ],
        ),
        migrations.CreateModel(
            name='Putt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('hole_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.holescore')),
            ],
        ),
        migrations.AddField(
            model_name='holescore',
            name='rnd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.round'),
        ),
    ]
