# Generated by Django 4.2.13 on 2024-06-27 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_tee_rating_alter_tee_slope'),
        ('round', '0003_round_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gir', models.BooleanField()),
                ('gld', models.BooleanField()),
                ('scrambling', models.BooleanField(null=True)),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.hole')),
                ('rnd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.round')),
            ],
        ),
        migrations.RemoveField(
            model_name='putt',
            name='hole_score',
        ),
        migrations.RemoveField(
            model_name='stroke',
            name='hole_score',
        ),
        migrations.DeleteModel(
            name='HoleScore',
        ),
        migrations.AddField(
            model_name='putt',
            name='hole_stats',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='round.holestats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stroke',
            name='hole_stats',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='round.holestats'),
            preserve_default=False,
        ),
    ]
