# Generated by Django 5.0.6 on 2024-06-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0004_holestats_remove_putt_hole_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stroke',
            name='penalty',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
