# Generated by Django 4.2.13 on 2024-06-24 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='Creation Date')),
                ('address', models.CharField(max_length=200)),
                ('par', models.IntegerField()),
                ('designer', models.CharField(max_length=200)),
                ('public', models.BooleanField()),
                ('bound_points', models.JSONField(blank=True, null=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
                ('num_holes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=200)),
                ('yardage', models.IntegerField(null=True)),
                ('slope', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.IntegerField()),
                ('nickname', models.CharField(blank=True, max_length=200, null=True)),
                ('par', models.IntegerField()),
                ('bound_points', models.JSONField(blank=True, null=True)),
                ('center_green_point', models.JSONField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
