# Generated by Django 4.2.13 on 2024-06-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tee',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tee',
            name='slope',
            field=models.FloatField(),
        ),
    ]
